name: wrddfolio_flutter
description: "Joe Ward Personal Portfolio Flutter Web"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Dependencies
  cupertino_icons: ^1.0.8
  video_player: ^2.9.5
  web: ^1.1.1
  http: ^1.3.0
  html: ^0.15.5
  url_strategy: ^0.3.0
  universal_html: ^2.2.4
  iconsax: ^0.0.8
  get: ^4.7.2
  intl: ^0.20.2
  lottie: ^3.3.1
  url_launcher: ^6.3.1
  connectivity_plus: ^6.1.3
  flutter_native_splash: ^2.4.5
  smooth_page_indicator: ^1.2.1
  animated_background: ^2.0.0
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.17
  firebase_core: ^3.12.1

# Dev Dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/
    - assets/JoeWardCV.pdf
