// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC803USFnJdYk4ebFxOf9TYa75VC8tHtW0',
    appId: '1:826792443900:web:a8abe01ba44e9e28473c79',
    messagingSenderId: '826792443900',
    projectId: 'wrddx-portfolio',
    authDomain: 'wrddx-portfolio.firebaseapp.com',
    storageBucket: 'wrddx-portfolio.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpqtIiF8bVMUcm0vNbxCOJpwIrdvEjd7s',
    appId: '1:826792443900:android:23a3af389eef1708473c79',
    messagingSenderId: '826792443900',
    projectId: 'wrddx-portfolio',
    storageBucket: 'wrddx-portfolio.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbrYn_WeFqOmVW_QWesYVWM0qXZ8c_WfE',
    appId: '1:826792443900:ios:5a269851543be566473c79',
    messagingSenderId: '826792443900',
    projectId: 'wrddx-portfolio',
    storageBucket: 'wrddx-portfolio.firebasestorage.app',
    iosBundleId: 'com.example.wrddfolioFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbrYn_WeFqOmVW_QWesYVWM0qXZ8c_WfE',
    appId: '1:826792443900:ios:5a269851543be566473c79',
    messagingSenderId: '826792443900',
    projectId: 'wrddx-portfolio',
    storageBucket: 'wrddx-portfolio.firebasestorage.app',
    iosBundleId: 'com.example.wrddfolioFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC803USFnJdYk4ebFxOf9TYa75VC8tHtW0',
    appId: '1:826792443900:web:c7c556da44bbe572473c79',
    messagingSenderId: '826792443900',
    projectId: 'wrddx-portfolio',
    authDomain: 'wrddx-portfolio.firebaseapp.com',
    storageBucket: 'wrddx-portfolio.firebasestorage.app',
  );
}
